Repository mindee/doctr, pull requests merged in 2022-06, with the labels that each got.

#937 Fix links in readme
  README.md
Labels: type: bug, topic: documentation

#936 add a Slack Community badge
  README.md
Labels: topic: documentation, type: new feature

#944 Update `io/pdf.py` to new pypdfium2 API
  doctr/io/pdf.py
  requirements-pt.txt
  requirements.txt
  setup.py
Labels: module: io, type: misc

#941 [Fix] PyTorch MASTER implementation
  doctr/models/recognition/master/pytorch.py
  doctr/models/recognition/transformer/pytorch.py
Labels: type: bug, help wanted, critical, module: models, framework: pytorch, topic: text recognition

#946 Add support page in README
  README.md
  img/doctr-need-help.png
Labels: type: misc

#933 [references] Add eval recognition and update eval detection scripts
  .github/workflows/references.yml
  doctr/datasets/utils.py
  references/detection/evaluate_pytorch.py
  references/detection/evaluate_tensorflow.py
  references/recognition/evaluate_pytorch.py
  references/recognition/evaluate_tensorflow.py
Labels: type: enhancement, ext: references, framework: pytorch, framework: tensorflow, topic: text detection, topic: text recognition

#953 update pypdfium2 dep and improve code quality
  doctr/io/pdf.py
  requirements-pt.txt
  requirements.txt
  setup.py
Labels: type: enhancement, topic: build, module: io, type: code quality

#958 docs: Documentation the reason for keras version specifier
  setup.py
Labels: topic: documentation, topic: build, framework: tensorflow

#956 [Fix] MJSynth dataset: filter corrupted or missing images
  doctr/datasets/mjsynth.py
Labels: type: bug, module: datasets

#955 [Fix] SVT dataset: clip box values and add shape and label check
  doctr/datasets/svt.py
Labels: type: bug, module: datasets

#963 chore: Updated TF requirements to fix grouped convolutions on CPU
  .github/workflows/references.yml
  requirements.txt
  setup.py
  tests/tensorflow/test_models_classification_tf.py
Labels: type: enhancement, topic: build, topic: ci, framework: tensorflow
